### ISSUE TITLE
Les catégories ne s'ajoutent pas lors de la création ou l'édition de tâche

### ISSUE THREAD

**Issue by un-sam-sauvage** [un-sam-sauvage/todo#8]
Lors de la création de tâche par les fixtures les catégories s'ajoutent bien, par contre une fois sur le site cela ne fonctionne pas.

Les catégories sont pourtant bien capturées par le formulaire et mise dans le taskRepository, mais rien n'arrive dans la base de donnée. 

Si l'on dump la tâche juste avant la redirection vers la liste des tâches, nous avons bien la / les catégories d'assignées correctement.

Si l'on essaie de find la tâche dans le TaskRepository par l'id, elle a bien les catégories. Par contre une fois la redirection faite, il n'y a plus rien. (même dans le render tout est dans le repository mais rien dans la base de données)

**Comment by charlesen** [comment]
C'était subtile, mais le bug est du à une particularité des type `Collections` (que l'on retrouve dans des relations ManyToOne et surtout ManyToMany)

En fait quand on sauvegardait une tache, la relation était bien sauvegardé du côté des Task, mais les catégories n'était jamais informées qu'elles devaient être associé à une catégorie (la méthode addCategory de l'entité Task n'est pas correctement appelé)... Cette particularité n'est vraie que si l'on passe par un formulaire.

Pour régler le soucis, il faut ajouter une petite propriété `by_reference` à `false` dans le TaskType comme ceci : 

```php
// src/Form/TaskType.php

->add('categories', null, 
[
  'by_reference' => false,
]);
```

Je te renvoie à la [documentation plus détaillée ici](https://symfony.com/doc/current/reference/forms/types/collection.html#by-reference) et [là aussi](https://symfony.com/doc/current/form/form_collections.html#handling-the-new-tags-in-php).

**Comment by un-sam-sauvage** [comment]
Merci ça a bien marché !
